[project]
name = "ml-server"
version = "1.0.0"
description = "Inference on Seldon MLServer"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "mlserver>=1.6.0",
    "ultralytics>=8.2.76"
]

[tool.pdm.scripts]
start = "mlserver start ml-server"
