[project]
name = "backend"
version = "1.0.0"
description = "FastAPI async backend"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "fastapi>=0.110.0",
    "aiohttp>=3.10.3",
    "opencv-python>=4.10.0.84",
    "numpy>=1.26.4",
    "uvicorn>=0.30.5",
    "celery>=5.4.0",
    "pika>=1.3.2",
    "redis>=5.0.8",
    "loguru>=0.7.2",

]

[tool.pdm.scripts]
start = "python3 -m backend"
worker = "celery -A backend.task worker --loglevel=info"
