name: Docker Compose CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Containerization with Docker Compose
        run: docker-compose up -d
      - name: Endpoint test
        run: |
          sleep 15
          docker run --network=host appropriate/curl -s http://0.0.0.0:8501/
